export default {
  getUsersByIds: "Error fetching users by Ids due to ",
  updateUserDevice: "Error updating user device due to ",
  Login: "Error login user due to ",
  Register: "Error registering user due to ",
  forgotPassword: "Error generating forgot password activation code due to ",
  codeVerification: "Error verifying code due to ",
  resetPassword: "Error resetting password due to ",
  resendCode: "Error resending verification code due to ",
  checkUsername: "An error occurred while checking the username due to  ",
  getUserData: "An error occurred while fetching user data due to ",
  getFollows: "Error getting follows/followers due to ",
  removeFollows: "Error removing follows/followers due to ",
  followUnfollow: "Error occured while following/unfollowing due to ",
  updateUser: "Error updating user due to ",
  deleteAccount: "Error deleting account due to ",
  changePass: "Error changing password due to ",
  userFeedback: "Error sending user feedback due to ",
  search: "Error occured while searching due to ",
  getNotification: "Error fetching notification due to ",
  regenerateJwtToken: "Error regenerating jwt token due to ",
  socialConnect: "Error connecting to socials due to ",
  isSocialConnect: "Error checking connected socials due to ",
  getConnectedSocials: "Error fetching connected socials due to ",
  getSocialFeeds: "Error fetching social feeds due to ",
  likeDislike: "Error liking/unliking due to ",
  fetchMore: "Error fetching more social feeds due to ",
  getLikes: "Error fetching likes due to ",
  savePortfolio: "Error saving portfolio due to ",
  deletePortfolio: "Error deleting portfolio due to ",
  checkName: "Error checking if name exists due to ",
  updatePortfolio: "Error updating portfolio due to ",
  getPortfolio: "Error occured while fetching portfolio due to ",
  arrangePortfolios: "Error arranging portfolios due to ",
  getPortfolios: "Error while fetching portfolios due to ",
  addPortImage: "Error while adding image to portfolio due to ",
  addUploadImg: "Error uploading image to portfolio due to ",
  createPOI: "Error creating point of intereest due to ",
  getPOIs: "Error fetching points of interest due to ",
  associatePOIs: "Error fetching associate POIs due to ",
  report: "Error reporting inappropriate conntent due to ",
  createEndFlashChallenge: "Error creating/ending flash challenge due to ",
  flashReminder: "Error sending flash challenge reminder due to ",
  flashSubmission: "Error submitting a flash challenge due to ",
  userSkipped: "Error skipping flash challenge due to ",
  getFlashSubmission: "Error fetching flash submission due to ",
  likeFlashSubmissions: "Error liking multiple flash submissions due to ",
  voteForSubmission: "Error occured while casting vote due to ",
  getWinners: "Error occured while fetching challenge winners due to ",
  getStats: "Error fetching flash stats due to ",
  addCategory: "Error adding category due to ",
  getCategories: "Error fetching categories due to ",
  deleteCategory: "Error deleting category due to ",
  createSponsor: "Error adding sponsor due to ",
  getSponsor: "Error fetching sponsors due to ",
  updateSponsor: "Error updating sponsor due to ",
  deleteSponsor: "Error deleting sponsor due to ",
  fetchAWSCredentials: "Error fetching aws credentials due to ",
};
